### ISSUE TITLE
wall mechanics

### ISSUE THREAD

**Issue by Ereiziark** [AspectsLove/spicychickenquest#8] opened 2021-07-29 00:40 UTC
In : https://spicychicken.quest/guides/group/mechanics/

Sometimes boss spawn adds in a line that will march forward. Players should find a safe spot, usually a hole in the wall

Saw in :
The vault
The Sunken Temple of Qarn (hard)

There can be other instances where you have to place yourself in a safe spot. In those instances it wont be adds but lasers or something like that

Saw in : 
Nier Raid

**Comment by sudomistress** [comment] 2021-07-29 00:56
Duplicate of #7

**Closed** 2021-07-29 00:56 UTC
Labels: duplicate
